package com.aboo.vnet.service.ws.service;

import javax.jws.WebParam;

import com.aboo.vnet.service.ws.model.Dog;

/**
 * Examples code for spring boot with CXF services. Hello is the interface for
 * sayHello interface. This class was generated by Apache CXF 3.1.0
 * 2015-05-18T13:02:03.098-05:00 Generated source version: 3.1.0
 */
public interface HelloService {

	Dog sayHello(@WebParam(name = "myname") String myname);
}
